
### Request for creatieng a patient
POST http://localhost:5000/patients
Content-type: application/json

{
  "name": "John Doe, Cap",
  "email": "ebrahim1@gmail.com",
  "address": "Cairo",
  "birthDate": "2003-02-06",
  "registrationDate": "2014-05-01"
}
###